#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1/noticeboard
#    username: root
#    password: 1234
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
# ?? ?? ??
server:
  port: 8080

# database ?? ??
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/noticeboard
    username: root
    password: 1234
  thymeleaf:
    cache: false
  mail:
    host: smtp.gmail.com # smtp 서버주소
    port: 587 # TLS - HTTPS = HTTP + TLS
    username: ${MAIL_USERNAME}  #발신자 구글계정
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true


  # spring data jpa ??
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework: INFO
    com.yourpackage: DEBUG
    org.springframework.security: DEBUG
